apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hackaton-video-processor-api-external-secret
  namespace: default
spec:
  refreshInterval: 72h
  secretStoreRef:
    name: hackaton-secret-store
    kind: SecretStore
  data:
  - secretKey: ENVIRONMENT
    remoteRef:
      key: 7Soat
      property: ENVIRONMENT
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: 7Soat
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: 7Soat
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: AWS_REGION
    remoteRef:
      key: 7Soat
      property: AWS_REGION
  - secretKey: AWS_S3_BUCKET
    remoteRef:
      key: 7Soat
      property: AWS_S3_BUCKET
  - secretKey: VIDEO_API_SQS_QUEUE_URL
    remoteRef:
      key: 7Soat
      property: VIDEO_API_SQS_QUEUE_URL
  - secretKey: VIDEO_API_SNS_TOPIC_ARN
    remoteRef:
      key: 7Soat
      property: VIDEO_API_SNS_TOPIC_ARN
  - secretKey: AWS_S3_REGION
    remoteRef:
      key: 7Soat
      property: AWS_S3_REGION
