apiVersion: v1
kind: Service
metadata:
  name: hackaton-video-processor-api-service-lb
spec:
  selector:
    app: hackaton-video-processor-api-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer