apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hackaton-prometheus-node-exporter-daemonset
  namespace: default
  labels:
    app: hackaton-prometheus-node-exporter-daemonset
spec:
  selector:
    matchLabels:
      app: hackaton-prometheus-node-exporter
  template:
    metadata:
      labels:
        app: hackaton-prometheus-node-exporter
    spec:
      containers:
      - name: hackaton-prometheus-node-exporter
        image: prom/node-exporter:v1.5.0
        ports:
        - name: metrics
          containerPort: 9100
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      hostNetwork: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
