apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackaton-prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackaton-prometheus
  template:
    metadata:
      labels:
        app: hackaton-prometheus
    spec:
      serviceAccountName: hackaton-prometheus-service-account
      containers:
        - name: hackaton-prometheus
          image: prom/prometheus:v2.53.1
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
          ports:
            - name: web
              containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: data-volume
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: hackaton-prometheus-config-map
        - name: data-volume
          emptyDir: {}
