apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hackaton-video-processor-worker-external-secret
  namespace: default
spec:
  refreshInterval: 72h
  secretStoreRef:
    name: hackaton-secret-store
    kind: SecretStore
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: 7Soat
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: 7Soat
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: AWS_REGION
    remoteRef:
      key: 7Soat
      property: AWS_REGION
  - secretKey: S3_REGION
    remoteRef:
      key: 7Soat
      property: AWS_S3_REGION
  - secretKey: SNS_TOPIC_ARN
    remoteRef:
      key: 7Soat
      property: SNS_TOPIC_ARN
  - secretKey: S3_VIDEO_BUCKET_NAME
    remoteRef:
      key: 7Soat
      property: S3_VIDEO_BUCKET_NAME
  - secretKey: S3_IMAGES_BUCKET_NAME
    remoteRef:
      key: 7Soat
      property: S3_IMAGES_BUCKET_NAME
  - secretKey: SQS_QUEUE_URL
    remoteRef:
      key: 7Soat
      property: SQS_QUEUE_URL
  - secretKey: SQS_DLQ_URL
    remoteRef:
      key: 7Soat
      property: SQS_DLQ_URL
  - secretKey: WORKER_POOL_SIZE
    remoteRef:
      key: 7Soat
      property: WORKER_POOL_SIZE
